### ISSUE TITLE
Привести код в порядок

### ISSUE THREAD

**Issue by oxeg** [lukaville/kurve-server#1]
Починить инспекции, убрать комментарии.
Подробнее тут: https://tech-mail.ru/blog/java/1316.html

**Comment by oxeg** [comment]
p.s. К комментариям типа // todo это не относится. Такие комменты допускаются

**Comment by lukaville** [comment]
Требуется убрать абсолютно все комментарии, кроме TODO?
Инспекции тоже абсолютно все подавить/исправить?

**Comment by oxeg** [comment]
Именно. Но если инспекции подавляете, нужно будет суметь обосновать подавление
