### ISSUE TITLE
utils.SessionManager#getSessionById почему получаете первый элемент именно так?

### ISSUE THREAD

**Issue by oxeg** [lukaville/kurve-server#3]
`return session.stream().findFirst();`

**Comment by oxeg** [comment]
А теперь нужно разобраться с исключением, которое кидает iterator().next(). Зачем обработчик этого исключения?

**Comment by lukaville** [comment]
Чтобы приложение не вылетело во время работы и дальнейший обработчик понял, что пользователь не авторизирован и отключил его.

**Comment by oxeg** [comment]
Ок. Но тогда зачем выводить стектрейс? Если это штатная ситуация, то намного дешевле проверить коллекцию на isEmpty() и возвращать null в таком случае. Если же ситуация нештатная и нам действительно нужно написать в лог об ошибке, лучше сделать осмысленное сообщение типа "Sessions for id %s not found"
