### ISSUE TITLE
frontend/AbstractServlet.java неужели нужны все эти методы?

### ISSUE THREAD

**Issue by oxeg** [lukaville/kurve-server#5]
Если есть какие-то, которые использовать не планируется, нужно их удалить

**Comment by lukaville** [comment]
Каждый метод с некоторой вероятностью может использоваться

**Comment by vitalii-kaplan** [comment]
> > Каждый метод с некоторой вероятностью может использоваться

не нужно писать методы заранее. если их никто не использует, в них будут ошибки. и никто об этом не узнает. 
когда, внезапно, кто-то начнет их вызывать, в надежде, что с ними все хорошо, вы можете получить очень странные баги.
